In [6]:
import pandas as pd
import os

# Testes e conclusões com o dataset

data_base = os.path.join('..', 'data', 'clima_bahia_hackathon(1).csv')

db = pd.read_csv(data_base)

db.describe()

,HORA (UTC),PRECIPITACAO TOTAL HORARIO (mm),"PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (W/m2),"TEMPERATURA DO AR - BULBO SECO, HORARIA (C)",TEMPERATURA DO PONTO DE ORVALHO (C),TEMPERATURA MAXIMA NA HORA ANT. (AUT) (C),TEMPERATURA MINIMA NA HORA ANT. (AUT) (C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIRECAO HORARIA (gr)","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
count,5.206752e+06,5.036677e+06,5.109466e+06,5.109226e+06,5.109226e+06,4.757215e+06,5.110934e+06,5.078667e+06,5.110690e+06,5.110691e+06,5.078058e+06,5.077117e+06,5.078729e+06,5.077665e+06,5.078995e+06,5.104256e+06,5.103967e+06,5.104368e+06
mean,1.150000e+03,-9.657275e+02,1.970921e+02,1.956048e+02,1.950892e+02,-3.610368e+03,-6.591853e+02,-7.605485e+02,-6.639641e+02,-6.649135e+02,-7.659409e+02,-7.697194e+02,-7.145337e+02,-7.228707e+02,-7.132326e+02,-7.014958e+02,-8.326478e+02,-8.263155e+02
std,6.922187e+02,2.953745e+03,2.810523e+03,2.813560e+03,2.813409e+03,6.294542e+03,2.527168e+03,2.681847e+03,2.536537e+03,2.535821e+03,2.691217e+03,2.695404e+03,2.703978e+03,2.707545e+03,2.697256e+03,2.798480e+03,2.771606e+03,2.756932e+03
min,0.000000e+00,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03,-9.999000e+03
25%,5.750000e+02,0.000000e+00,9.520000e+02,9.523000e+02,9.517000e+02,-9.999000e+03,2.090000e+01,1.490000e+01,2.140000e+01,2.050000e+01,1.550000e+01,1.430000e+01,5.400000e+01,4.600000e+01,5.000000e+01,7.400000e+01,2.500000e+00,8.000000e-01
50%,1.150000e+03,0.000000e+00,9.669000e+02,9.671000e+02,9.666000e+02,1.160000e+01,2.380000e+01,1.830000e+01,2.440000e+01,2.330000e+01,1.870000e+01,1.780000e+01,7.500000e+01,6.700000e+01,7.100000e+01,1.170000e+02,4.900000e+00,1.900000e+00
75%,1.725000e+03,0.000000e+00,9.932000e+02,9.935000e+02,9.929000e+02,1.502300e+03,2.720000e+01,2.050000e+01,2.800000e+01,2.640000e+01,2.090000e+01,2.000000e+01,8.900000e+01,8.400000e+01,8.700000e+01,1.680000e+02,7.200000e+00,3.200000e+00
max,2.300000e+03,8.520000e+01,1.049200e+03,1.049900e+03,1.047800e+03,5.158800e+04,4.500000e+01,4.500000e+01,4.500000e+01,4.500000e+01,4.500000e+01,4.500000e+01,1.000000e+02,1.000000e+02,1.000000e+02,3.600000e+02,4.680000e+01,1.920000e+01

In [10]:
db[db['PRECIPITACAO TOTAL HORARIO (mm)'] > 0].head(20)

,ESTACAO,DATA (YYYY-MM-DD),HORA (UTC),PRECIPITACAO TOTAL HORARIO (mm),"PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (W/m2),"TEMPERATURA DO AR - BULBO SECO, HORARIA (C)",TEMPERATURA DO PONTO DE ORVALHO (C),TEMPERATURA MAXIMA NA HORA ANT. (AUT) (C),TEMPERATURA MINIMA NA HORA ANT. (AUT) (C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIRECAO HORARIA (gr)","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
153,A401,2021-01-07,900,0.2,1007.4,1007.4,1006.9,45.5,23.9,21.0,24.6,23.9,21.1,20.4,84.0,79.0,84.0,82.0,1.3,0.6
181,A401,2021-01-08,1300,5.2,1008.4,1008.4,1008.2,580.3,25.0,23.1,28.6,25.0,23.4,21.7,90.0,67.0,89.0,146.0,5.6,1.0
182,A401,2021-01-08,1400,25.8,1008.0,1008.6,1008.0,399.2,25.3,24.2,25.3,24.2,24.2,22.7,94.0,89.0,94.0,141.0,3.9,0.5
183,A401,2021-01-08,1500,0.2,1007.1,1008.0,1007.1,2847.3,28.0,26.3,28.1,25.3,26.7,24.5,94.0,91.0,91.0,90.0,3.7,0.9
249,A401,2021-01-11,900,3.6,1006.6,1006.7,1006.1,48.8,23.6,22.4,25.0,23.5,22.6,22.2,93.0,87.0,93.0,31.0,5.4,1.2
251,A401,2021-01-11,1100,0.2,1007.5,1007.5,1007.0,1079.0,26.3,24.5,26.9,24.1,25.4,22.9,94.0,89.0,90.0,50.0,4.2,1.3
275,A401,2021-01-12,1100,29.6,1007.9,1007.9,1006.9,47.6,22.9,21.8,25.5,22.9,24.2,21.8,94.0,91.0,94.0,75.0,6.7,1.1
276,A401,2021-01-12,1200,15.8,1008.3,1008.6,1007.9,162.4,23.2,22.4,23.2,22.6,22.4,21.7,95.0,94.0,95.0,4.0,5.3,0.6
277,A401,2021-01-12,1300,3.0,1008.4,1008.8,1008.3,1118.4,24.2,23.2,25.1,23.1,24.3,22.3,96.0,94.0,94.0,86.0,3.0,0.5
281,A401,2021-01-12,1700,0.2,1006.1,1006.7,1006.1,2327.4,27.2,23.8,27.8,26.6,24.6,23.0,86.0,80.0,82.0,325.0,4.3,1.2
297,A401,2021-01-13,900,1.4,1006.5,1006.5,1005.9,88.1,23.7,22.4,24.3,23.5,22.8,22.2,93.0,91.0,93.0,359.0,2.4,0.3
302,A401,2021-01-13,1400,0.2,1007.8,1008.2,1007.8,3398.2,29.9,23.0,29.9,27.0,24.2,21.9,82.0,64.0,67.0,67.0,5.5,1.4
340,A401,2021-01-15,400,0.8,1006.2,1006.8,1006.2,NaN,24.7,23.2,25.6,24.6,23.3,22.6,92.0,86.0,92.0,93.0,5.5,1.1
341,A401,2021-01-15,500,1.6,1005.6,1006.2,1005.6,NaN,24.4,23.2,24.7,24.1,23.2,22.9,94.0,92.0,94.0,61.0,4.5,1.0
342,A401,2021-01-15,600,4.8,1005.5,1005.6,1005.3,NaN,23.9,22.9,24.6,23.9,23.6,22.9,94.0,93.0,94.0,50.0,4.9,1.9
343,A401,2021-01-15,700,27.2,1005.5,1005.6,1005.3,NaN,23.8,22.9,23.9,23.6,23.1,22.8,95.0,94.0,95.0,109.0,5.7,1.2
344,A401,2021-01-15,800,31.2,1006.0,1006.0,1005.5,0.2,23.7,22.9,23.8,23.1,23.0,22.3,96.0,95.0,96.0,54.0,6.4,1.5
345,A401,2021-01-15,900,0.2,1006.6,1006.6,1005.8,34.5,23.5,22.8,23.7,23.5,23.0,22.8,96.0,96.0,96.0,52.0,6.1,2.0
346,A401,2021-01-15,1000,0.2,1006.6,1006.8,1006.4,269.8,24.3,23.4,24.3,23.5,23.4,22.7,96.0,95.0,95.0,66.0,5.8,1.8
347,A401,2021-01-15,1100,0.6,1006.9,1006.9,1006.5,659.9,24.4,23.5,24.5,24.0,23.6,23.1,95.0,94.0,95.0,57.0,8.0,2.4